# syntax default values
language:
  default_variable: "_"
  default_sort_order: "desc"
  default_datasource_schema: "stixshifter"
  default_analytics_schema: "docker"

# how a Kestrel session is executed
session:
  cache_directory_prefix: "kestrel-session-" # under system temp directory
  local_database_path: "local.db"
  show_execution_summary: true

# whether/how to prefetch all records/observations for entities
prefetch:

  # enable/disable prefetch for command
  #
  # If prefetch is enabled, Kestrel will send additional queries to the data
  # source to search for related records regarding entities retrieved from the
  # user-specified pattern, collecting more complete information (attributes,
  # connections to other entities) of the entities from different records.
  switch_per_command:
    get: true
    find: true

  # declare the list of entity types to not prefetch
  excluded_entities:
    -
    # - file
    # - process

  # Detailed logic to identify the same process from different records is more
  # complex than many data source query language can express, so Kestrel
  # retrieves potential same process candidate records and perform fine-grained
  # process identification in Kestrel with these parameters.
  process_identification:
    pid_but_name_changed_time_begin_offset: -5 # seconds
    pid_but_name_changed_time_end_offset: 5 # seconds
    pid_and_name_time_begin_offset: -3600 # seconds
    pid_and_name_time_end_offset: 3600 # seconds
    pid_and_ppid_time_begin_offset: -3600 # seconds
    pid_and_ppid_time_end_offset: 3600 # seconds
    pid_and_name_and_ppid_time_begin_offset: -86400 # seconds
    pid_and_name_and_ppid_time_end_offset: 86400 # seconds

# option when generating STIX query
stixquery:
  timerange_start_offset: -300 # seconds
  timerange_stop_offset: 300 # seconds
  support_id: false # STIX 2.0 does not support unique ID

# debug options
debug:
  env_var: "KESTREL_DEBUG" # debug mode if the environment variable exists
  cache_directory_prefix: "kestrel-" # under system temp directory
  session_exit_marker: "session.exited"
  maximum_exited_session: 3
