# syntax default values
language:
  default_sort_order: "desc"

# debug options
debug:
  env_var: "KESTREL_DEBUG" # debug mode if the environment variable exists
  cache_directory_path: "~/kestrel-debug-session" # put in user's home directory by default

# default identifier attribute(s) of an entity across all datasource interfaces
# if multiple attributes are specified, logic AND will be added in between
# each datasource interface config could have the same section to override this
entity_identifier:
  file: "hashes[?algorithm_id == 3]" # sha256
  group: uid
  process: uid
  endpoint: ip
  device: ip
  src_endpoint:
    - ip
    - port
  src_endpoint:
    - ip
    - port
  certificate: serial_number
  user: uid
