# syntax default values
language:
  default_sort_order: "desc"

# debug options
debug:
  env_var: "KESTREL_DEBUG" # debug mode if the environment variable exists
  cache_directory_path: "~/kestrel-debug-session" # put in user's home directory by default

# default identifier attribute(s) of an entity across all datasource interfaces
# always provide a list as identifiers even it is a single identifier
# if multiple attributes are specified, logic AND will be added in between
entity_identifier:
  endpoint:
    - uid
  file: # "hashes[?algorithm_id == 3]" # sha256
    - name
    - endpoint.uid
  group:
    - uid
  process:
    - uid
    - endpoint.uid
  src_endpoint:
    - ip
    - port
  dst_endpoint:
    - ip
    - port
  certificate:
    - serial_number
  user:
    - uid
  email:
    - uid
