name: Code Coverage Evaluation on PR

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
    types:
      - opened
      - edited
      - reopened
      - synchronize
      - unlocked

jobs:
  codecov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Kestrel
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install .
      - name: Coverage report generation
        run: |
          python -m pip install pytest-cov "stix-shifter-modules-elastic-ecs>=4.6.0,<5.0.0"
          # pytest-cov does not support automatic sub-package recognition in src/
          # pass in all sub-package names through multiple --cov arguments
          # use ls, xargs, and sed carefully regarding diff between mac/BSD and linux
          python -m pytest -vv --cov-report=xml $(ls src | grep -v '.egg-info' | xargs | sed -r 's/^| / --cov=/g')
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
          verbose: true
