name: Code style compliance check

on:
  push:
    branches:
      - develop
      - develop_*
    paths:
      - 'packages/*/src/**'
  pull_request:
    branches:
      - develop
      - develop_*
    paths:
      - 'packages/*/src/**'
    types:
      - opened
      - reopened
      - synchronize

jobs:
  codestyle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Install Kestrel package
        run: |
          pip install --upgrade pip setuptools wheel
          pip install black
      - name: Code style check (please black your code)
        run: black --check packages/*/src/
