name: Publish to PyPI

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    strategy:
      matrix:
        package:
          - kestrel_core
          - kestrel_datasource_stixbundle
          - kestrel_datasource_stixshifter
          - kestrel_analytics_python
          - kestrel_analytics_docker
          - kestrel_jupyter
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./packages/${{ matrix.package }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Install building environment
        run: |
          pip install --upgrade pip setuptools wheel
          pip install --upgrade build twine
      - name: Build and publish
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          # `build` is installed as a Python module, not a standalone commandline
          python -m build --sdist --wheel --outdir dist/ .
          twine check dist/*
          twine upload --verbose --skip-existing dist/*
