name: Unit testing on PR

on:
  push:
    branches:
      - develop
      - develop_*
    paths:
      - 'packages-nextgen/**'
  pull_request:
    branches:
      - develop
      - develop_*
    paths:
      - 'packages-nextgen/**'
    types:
      - opened
      - reopened
      - synchronize

jobs:
  test-kestrel-core:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12']
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
        working-directory: ./packages-nextgen/kestrel_core
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Python Tools
        run: pip install --upgrade pip setuptools wheel pytest
      - name: Install kestrel_core
        run: pip install .
      - name: Unit testing
        run: pytest -vv

  test-kestrel-interface-opensearch:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12']
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
        working-directory: ./packages-nextgen/kestrel_interface_opensearch
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Python Tools
        run: pip install --upgrade pip setuptools wheel pytest
      - name: Install kestrel_core
        working-directory: ./packages-nextgen/kestrel_core
        run: pip install .
      - name: Install kestrel_interface_opensearch
        run: pip install .
      - name: Unit testing
        run: pytest -vv
