name: Unit testing on PR

on:
  push:
    branches:
      - develop
      - develop_*
    paths:
      - 'src/**'
      - 'bin/**'
      - 'tests/**'
  pull_request:
    branches:
      - develop
      - develop_*
    paths:
      - 'src/**'
      - 'bin/**'
      - 'tests/**'
    types:
      - opened
      - reopened
      - synchronize

jobs:
  unittest:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ['3.8', '3.9', '3.10', '3.11']
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Kestrel
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install .
      - name: Unit testing
        run: |
          python -m pip install pytest
          python -m pytest -vv
