name: Unused imports check

on:
  push:
    branches:
      - develop
      - develop_*
    paths:
      - 'packages/*/src/**'
  pull_request:
    branches:
      - develop
      - develop_*
    paths:
      - 'packages/*/src/**'
    types:
      - opened
      - reopened
      - synchronize

jobs:
  unusedimports:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Install Kestrel package
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install unimport
      - name: Check
        run: python -m unimport --check --exclude __init__.py packages/*/src/
